export const siteConfig = {
  name: "Vietnam Tax Advisory",
  shortName: "VTA",
  legalName: "Vietnam Tax Advisory Co., Ltd",
  tagline: "Accounting, Tax & CFO Advisory for Foreign-Owned Companies in Vietnam",
  description:
    "Vietnam-based accounting, tax, payroll, transfer pricing, and CFO advisory for foreign investors, FDI companies, startups, and regional headquarters. English-speaking team with Big-4 heritage.",
  url: "https://accounting-agency.investvietnam.co",
  ogImage: "/og-image.svg",
  logo: "/logo.svg",
  locale: "en",
  email: "hello@vietnamtaxadvisory.com",
  phone: "+84 (0) 28 3822 0000",
  whatsapp: "+84 28 3822 0000",
  calendlyUrl: "https://calendly.com/vietnamtaxadvisory/intro",
  crmWebhook: process.env.NEXT_PUBLIC_CRM_WEBHOOK || "",
  address: {
    street: "Bitexco Financial Tower, 2 Hai Trieu Street",
    district: "District 1",
    city: "Ho Chi Minh City",
    region: "Ho Chi Minh City",
    country: "Vietnam",
    countryCode: "VN",
    postal: "700000",
    geo: { latitude: 10.7718, longitude: 106.7009 },
  },
  social: {
    linkedin: "https://www.linkedin.com/company/vietnamtaxadvisory",
  },
  founders: [
    {
      name: "Linh Nguyen",
      role: "Managing Partner",
      credentials: "CPA Vietnam, Big-4 alumni, 14 years Vietnam tax practice",
      bio: "Linh founded Vietnam Tax Advisory in 2014 after a decade at a Big-4 firm in Ho Chi Minh City. She leads the firm's tax practice with a focus on FDI companies, transfer pricing, and GDT audit defence. She has represented foreign-owned companies in tax audits, tax appeals, and advance pricing agreements, and is a regular contributor to industry publications on Vietnam tax.",
      expertise: ["CIT", "Transfer Pricing", "Tax Audit Defence", "FDI Tax"],
      slug: "linh-nguyen",
    },
    {
      name: "Marc Schneider",
      role: "Head of International Advisory",
      credentials: "CFA, former PwC Singapore, regional FDI specialist",
      bio: "Marc leads our international advisory practice from Singapore, supporting regional headquarters across Southeast Asia, Australia, and Japan. He specialises in entity structuring, cross-border tax planning, and group reporting integration. Before joining VTA he spent eight years at PwC Singapore advising Japanese, Korean, and Australian multinationals on their Vietnam market entry.",
      expertise: ["Cross-border Tax", "Entity Structuring", "Group Reporting", "M&A Tax"],
      slug: "marc-schneider",
    },
  ],
  team: [
    {
      name: "Mai Tran",
      role: "Senior Tax Manager",
      credentials: "CPA Vietnam, MOF Tax Agent Licence",
      bio: "Mai leads monthly CIT, VAT, and FCT compliance for our FDI client portfolio. She joined VTA from a Big-4 firm in 2017 and has run over 300 monthly compliance cycles for foreign-owned companies.",
      expertise: ["CIT", "VAT", "FCT", "Monthly Compliance"],
      slug: "mai-tran",
    },
    {
      name: "Hiro Tanaka",
      role: "Senior Transfer Pricing Manager",
      credentials: "MA Tax (Kyoto), CbCR certified",
      bio: "Hiro leads our transfer pricing practice, with particular focus on Japanese and Korean manufacturing clients. He has prepared over 100 Local Files and Master Files and represented clients in TP audits and APAs.",
      expertise: ["Transfer Pricing", "CbCR", "Manufacturing", "Japanese clients"],
      slug: "hiroshi-tanaka",
    },
    {
      name: "Sarah Williams",
      role: "CFO Advisory Lead",
      credentials: "CA ANZ, former KPMG Australia",
      bio: "Sarah leads the virtual CFO practice, working with foreign-owned companies on board reporting, cash forecasting, and fundraising readiness. She came to VTA from KPMG Melbourne where she audited Australian-listed companies in retail, SaaS, and financial services.",
      expertise: ["Virtual CFO", "Board Reporting", "IFRS", "Australian clients"],
      slug: "sarah-williams",
    },
    {
      name: "David Pham",
      role: "Payroll & HR Compliance Lead",
      credentials: "LLB, Vietnam bar, 9 years payroll practice",
      bio: "David leads the payroll practice, focusing on expatriate tax equalisation, social insurance, and labour-authority audits. He has managed payroll for companies with up to 400 employees across Vietnam.",
      expertise: ["Payroll", "PIT", "Social Insurance", "Work Permits"],
      slug: "david-pham",
    },
    {
      name: "Priya Sharma",
      role: "Setup & Licensing Manager",
      credentials: "LLM International Business Law",
      bio: "Priya leads the company setup practice, with responsibility for IRC and ERC applications, branch registrations, and work permits. She has set up over 200 foreign-owned companies in Vietnam.",
      expertise: ["IRC", "ERC", "Company Setup", "Work Permits"],
      slug: "priya-sharma",
    },
    {
      name: "James O'Brien",
      role: "US/UK Tax Specialist",
      credentials: "CPA (US), ACA (UK), former EY New York",
      bio: "James supports US and UK parent companies with their Vietnam entities, with a focus on FCPA, SOX, and inter-company documentation. He came to VTA from EY New York where he specialised in international tax.",
      expertise: ["US Tax", "UK Tax", "SOX", "FCPA"],
      slug: "james-obrien",
    },
  ],
  advisoryBoard: [
    {
      name: "Dr. Nguyen Van Minh",
      role: "Senior Advisor — Tax Policy",
      credentials: "PhD Taxation (LSE), former MoF official",
      bio: "Dr. Nguyen is a retired director from the Ministry of Finance with 30 years of experience in tax policy and administration. He advises the firm on regulatory developments and represents clients in high-level engagements with the General Department of Taxation.",
      expertise: ["Tax Policy", "GDT Relations", "APA Negotiation"],
      slug: "dr-nguyen-van-minh",
    },
    {
      name: "Eileen Chua",
      role: "Senior Advisor — Cross-border M&A",
      credentials: "Partner (non-executive), former Mayer Brown HK",
      bio: "Eileen advises the firm on cross-border M&A, FDI structuring, and joint venture negotiations. She spent 22 years as a partner at a major international law firm in Hong Kong.",
      expertise: ["M&A Tax", "Joint Ventures", "Cross-border Structuring"],
      slug: "eileen-chua",
    },
  ],
  foundedYear: 2014,
  serviceAreas: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Binh Duong",
    "Dong Nai",
    "Ba Ria-Vung Tau",
    "Can Tho",
    "Hai Phong",
  ],
  geoEntities: [
    "Vietnam",
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Binh Duong",
    "Dong Nai",
    "Ba Ria-Vung Tau",
    "Can Tho",
    "Hai Phong",
    "Southeast Asia",
    "ASEAN",
  ],
  expertiseEntities: [
    "Accounting",
    "Tax",
    "Payroll",
    "Social Insurance",
    "VAT",
    "Corporate Income Tax",
    "Personal Income Tax",
    "Transfer Pricing",
    "Foreign Contractor Tax",
    "Statutory Audit",
    "Bookkeeping",
    "CFO Advisory",
    "Compliance",
    "FDI",
    "Foreign Direct Investment",
    "Company Formation",
    "IRC",
    "ERC",
    "Work Permits",
    "Profit Repatriation",
    "Payroll Tax",
    "Expatriate Tax",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
