export const siteConfig = {
  name: "Vietnam Tax Advisory",
  shortName: "VTA",
  legalName: "Vietnam Tax Advisory Co., Ltd",
  tagline: "Accounting, Tax & Advisory for Foreign-Owned Companies in Vietnam",
  description:
    "Vietnam-based accounting, tax, payroll, transfer pricing, and advisory services for foreign investors and FDI companies in Vietnam.",
  url: "https://accounting-agency.investvietnam.co",
  ogImage: "/og-image.svg",
  logo: "/logo.svg",
  locale: "en",
  email: "hello@vietnamtaxadvisory.com",
  phone: "+84 (0) 28 3822 0000",
  whatsapp: "+84 28 3822 0000",
  calendlyUrl: "https://calendly.com/vietnamtaxadvisory/intro",
  crmWebhook: process.env.NEXT_PUBLIC_CRM_WEBHOOK || "",
  address: {
    street: "Bitexco Financial Tower, 2 Hai Trieu Street",
    district: "District 1",
    city: "Ho Chi Minh City",
    region: "Ho Chi Minh City",
    country: "Vietnam",
    countryCode: "VN",
    postal: "700000",
    geo: { latitude: 10.7718, longitude: 106.7009 },
  },
  social: {
    linkedin: "https://www.linkedin.com/company/vietnamtaxadvisory",
  },
  // No team, founders, or advisory board published. Real team profiles will be
  // added only with verified names, credentials, and consent.
  team: [] as ReadonlyArray<{ name: string; slug: string; role: string; bio?: string }>,
  foundedYear: 2014,
  serviceAreas: [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Binh Duong",
    "Dong Nai",
    "Ba Ria-Vung Tau",
    "Can Tho",
    "Hai Phong",
  ],
  geoEntities: [
    "Vietnam",
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Binh Duong",
    "Dong Nai",
    "Ba Ria-Vung Tau",
    "Can Tho",
    "Hai Phong",
    "Southeast Asia",
    "ASEAN",
  ],
  expertiseEntities: [
    "Accounting",
    "Tax",
    "Payroll",
    "Social Insurance",
    "VAT",
    "Corporate Income Tax",
    "Personal Income Tax",
    "Transfer Pricing",
    "Foreign Contractor Tax",
    "Statutory Audit",
    "Bookkeeping",
    "Compliance",
    "FDI",
    "Foreign Direct Investment",
    "Company Formation",
    "Work Permits",
    "Profit Repatriation",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
